run:
	g++ -o KolejkaTest.o KolejkaTest.cpp
	./KolejkaTest.o
	@echo 
	@make clean

clean:                                                     
	rm -f *.o  *~ *.a *.so *.x core core* a.out; rm -rf ${LIB_DIR}