run:
	g++ -c Edge.cpp -o Edge.o
		g++ -c GraphAsMatrix.cpp -o GraphAsMatrix.o
	g++ -o GrafyTest.o GrafyTest.cpp Edge.cpp
	./ZbioryTest.o
	@echo 
	@make clean

clean:                                                     
	rm -f *.o  *~ *.a *.so *.x core core* a.out; rm -rf ${LIB_DIR}